# Generated by Django 6.0.7 on 2026-08-06 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('jobTitle', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('dateApplied', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Successful'), ('I', 'Interviewing'), ('R', 'Rejected')], max_length=2)),
                ('companyContact', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
